In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('June_stringIndexer.csv')

In [4]:
df = df.drop(['Vehicle Year', 'Intersecting Street', 'Unnamed: 0'], axis =1)

In [5]:
df

Violation Code  Violation Location House Number  Registration State  \
0                  63                 1.0          109                  35   
1                  63                 1.0          109                  39   
2                  63                 1.0          109                  35   
3                  63                 1.0          109                  35   
4                  63                 1.0          109                  35   
...               ...                 ...          ...                 ...   
48481              40                75.0          598                  23   
48482              20                75.0         1285                  13   
48483              40                75.0         1152                  39   
48484              53                75.0          590                  44   
48485              53                75.0          590                  13   

       Vehicle Body Type  Vehicle Make  Violation Time  Violation County  \
0                     70            83            1298                 4   
1                     75            96            1250                 4   
2                     70            72            1280                 4   
3                     -1            83            1246                 4   
4                     -1            72            1268                 4   
...                  ...           ...             ...               ...   
48481                  1           110             293                 2   
48482                  1             7             106                 2   
48483                 75           110             280                 2   
48484                 70           121             762                 2   
48485                 70            -1             776                 2   

       Street Name  Vehicle Color  
0             2376             58  
1             2376             -1  
2             2376             26  
3             2376             -1  
4             2376             26  
...            ...            ...  
48481         2567             18  
48482          949            130  
48483         1261            124  
48484         1354             65  
48485         1354             26  

[48486 rows x 10 columns]

In [12]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [21]:
x = df.drop('Violation Code', axis=1)
x.columns

Index(['Violation Location', 'House Number', 'Registration State',
       'Vehicle Body Type', 'Vehicle Make', 'Violation Time',
       'Violation County', 'Street Name', 'Vehicle Color'],
      dtype='object')

In [57]:
x = df[['Violation Location', 'Registration State','Vehicle Body Type', 'Vehicle Make', 'Violation Time','Violation County', 'Street Name', 'Vehicle Color']]

In [58]:
x = x.fillna(0)

In [59]:
y = df['Violation Code']

In [13]:
y.unique()

array([63, 65, 14, 70, 46, 20, 40, 48, 17, 74, 84, 16, 71, 31, 69, 81, 10,
       38, 21, 19, 42, 51, 53, 75, 67, 72, 37, 82, 68, 98, 76, 24, 41, 11,
       33, 35, 99, 50, 62, 60, 18, 83, 66, 91, 27, 78, 95, 47, 61, 79, 39,
        6, 85, 90, 73, 13, 22, 80, 96,  4, 87, 89, 26, 77, 52, 45, 49, 97,
       23,  9, 58, 34, 44, 64,  8, 57])

1917389

In [60]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x,
    y, 
    test_size = 0.2,
    random_state=42
)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(38788, 8) (38788,)
(9698, 8) (9698,)


In [54]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import f1_score

from sklearn.impute import SimpleImputer, MissingIndicator

from sklearn.pipeline import FeatureUnion, make_pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

In [45]:
transformer = FeatureUnion(
    transformer_list=[
         ('features', SimpleImputer(strategy='mean')),
         ('indicators', MissingIndicator())])
transformer = transformer.fit(X_train, Y_train)
results = transformer.transform(X_test)
results.shape

(9698, 9)

In [47]:
clf = make_pipeline(transformer, DecisionTreeClassifier())
clf = clf.fit(X_train, Y_train)
results = clf.predict(X_test)
results.shape

(9698,)

In [48]:
dec_tree_score = f1_score(Y_test, results, average=None)

In [49]:
dec_tree_score

array([0.        , 0.41666667, 0.        , 0.4516129 , 0.28571429,
       0.35294118, 0.40212342, 0.45686901, 0.30985915, 0.24137931,
       0.31704669, 0.51676301, 0.66501941, 0.15384615, 0.        ,
       0.42424242, 0.        , 0.14285714, 0.5210084 , 0.        ,
       0.22939068, 0.42392344, 0.        , 0.2860425 , 0.16666667,
       0.28571429, 1.        , 0.36363636, 0.31936416, 0.66101695,
       0.36018957, 0.        , 0.11428571, 0.2254902 , 0.        ,
       0.25      , 0.28571429, 0.        , 0.        , 0.66666667,
       0.        , 0.        , 0.12658228, 0.37209302, 0.52401747,
       0.12851406, 0.15584416, 0.125     , 0.35714286, 0.13907285,
       0.04878049, 0.375     , 0.        , 0.36158192, 0.        ,
       0.        , 0.        , 0.17241379, 0.        , 0.21428571,
       0.25      , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.29697766, 0.22222222])

In [56]:
dframe = pd.DataFrame({'Actual':Y_test,'Predict':results})
print("Test R-squared: ",round(metrics.r2_score(Y_test,results),2))
print("Test Explained Variation: ",round(metrics.explained_variance_score(Y_test,results),2))
dframe

Test R-squared:  -0.32
Test Explained Variation:  -0.32


Actual  Predict
26100      20       22
3085       98       46
33358      70       40
17599      98       98
30937      38       38
...       ...      ...
47557      14       46
46605      37       40
26725      20       48
17324      18       38
38777      38       38

[9698 rows x 2 columns]

In [61]:
dec_tree = DecisionTreeClassifier()
dec_tree = dec_tree.fit(X_train, Y_train)

In [62]:
dec_tree_pred = dec_tree.predict(X_test)

dec_tree_score = f1_score(Y_test, dec_tree_pred, average=None)

In [64]:
dec_tree_pred



array([22, 48, 40, ..., 48, 38, 38])

In [65]:
dec_tree_score

array([0.        , 0.38095238, 0.        , 0.44067797, 0.28571429,
       0.42857143, 0.39733333, 0.46349206, 0.30042918, 0.21052632,
       0.31590181, 0.51378299, 0.66363318, 0.2       , 0.        ,
       0.4516129 , 0.        , 0.15384615, 0.52601156, 0.        ,
       0.24043716, 0.42699856, 0.        , 0.29530979, 0.16666667,
       0.26086957, 1.        , 0.30769231, 0.32524964, 0.66666667,
       0.31279621, 0.        , 0.1025641 , 0.22680412, 0.        ,
       0.27160494, 0.18181818, 0.        , 0.        , 0.66666667,
       0.        , 0.0952381 , 0.1       , 0.41935484, 0.53389831,
       0.13078471, 0.16363636, 0.125     , 0.43478261, 0.13793103,
       0.04761905, 0.375     , 0.        , 0.39583333, 0.        ,
       0.        , 0.        , 0.14035088, 0.        , 0.21238938,
       0.28571429, 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.28954424, 0.19354839])

In [67]:
dframe = pd.DataFrame({'Actual':Y_test,'Predict':dec_tree_pred})
print('Accuracy score', metrics.accuracy_score(Y_test, dec_tree_pred))
dframe

Accuracy score 0.38461538461538464


Actual  Predict
26100      20       22
3085       98       48
33358      70       40
17599      98       98
30937      38       38
...       ...      ...
47557      14       46
46605      37       40
26725      20       48
17324      18       38
38777      38       38

[9698 rows x 2 columns]

In [69]:
dec_tree.score(X_train, Y_train)

0.9914664329173971